on:
  push:
    branches: main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout build branch
        uses: actions/checkout@v2
        with:
          ref: 'build'
      
      - name: Clone repo
        run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git /tmp/repo

      - name: Make new file
        run: |
          cd /tmp/repo
          echo "xd" > test
          cat test

      - name: Push
        run: |
          git add .
          git commit -m "testxd"
          git push -f
