on:
  push:
    branches: main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout build branch
        uses: actions/checkout@v2
        with:
          ref: 'build'
      
      - name: Test make new file
        run: touch test
