on:
  push:
    branches: main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Clone repo and get build branch
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git $RUNNER_TEMP/repo
          cd $RUNNER_TEMP/repo
          git fetch -u origin build:build
          git checkout build

      - name: Build Angular app
        run: |
          npm install
          npm run-script build

      - name: Clean directory for Github Pages
        run: |
          mkdir tmp
          mv ./* tmp/
          mv tmp/dist/site-xd/* ./
          mv tmp/CNAME ./
          rm -rf tmp/

      - name: Push
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "build commit ${GITHUB_SHA:0:7}"
          git push -f
