on:
  push:
    branches: main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout build branch
        uses: actions/checkout@v2
        with:
          ref: 'build'
      
      - name: Clone repo and get build branch
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git /tmp/repo
          cd /tmp/repo
          git fetch -u origin build:build
          git checkout build

      - name: Make new file
        run: |
          echo "xd" > test
          cat test

      - name: Push
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "build test"
          git push -f
