on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up git config
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Fetch build branch
        run: |
          cd ${{ github.workspace }}
          git fetch
          git switch build

      - name: Clean build branch
        run: |
          shopt -s extglob
          rm -rf ./*

      - name: Merge main into build
        run: git merge -X theirs --no-commit main --allow-unrelated-histories

      - name: Build Angular app
        run: |
          npm install
          npm run-script build

      - name: Clean up
        run: |
          rm -r !(dist|CNAME)
          shopt -s dotglob
          mv dist/*/* ./
          rm -r dist
          shopt -u dotglob

      - name: Push
        run: |
          git add .
          git commit -m "build commit ${GITHUB_SHA:0:7}"
          git push -f -u origin build
