on:
  push:
    branches: main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@build

      - name: test
        run: git checkout
