on:
  push:
    branches: main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout build branch
        uses: actions/checkout@v2
        with:
          ref: 'build'
      
      - name: Make and push new file
        run: |
          echo "xd" > test
          cat test
          git add .
          git commit -c "testxd"
          git push -f
