on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch build branch
        run: |
          cd ${{ github.workspace }}
          git fetch build:build
          git checkout build
          git reset --hard ${{ github.sha }}

      - name: Build Angular app
        run: |
          npm install
          npm run-script build

      - name: Clean up
        run: |
          shopt -s extglob dotglob
          rm -r !("dist" | "CNAME")
          shopt -u dotglob
          mv dist/*/* ./
          rmdir dist
