on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch build branch
        run: |
          cd ${{ github.workspace }}
          git checkout -b build
          git reset --hard ${{ github.sha }}

      - name: Build Angular app
        run: |
          npm install
          npm run-script build

      - name: Clean up
        run: |
          shopt -s extglob
          rm -r !(dist|CNAME)
          shopt -s dotglob
          mv dist/*/* ./
          rm -r dist
          shopt -u dotglob
