on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch build branch
        run: |
          cd ${{ github.workspace }}
          git fetch
          git switch build

      - name: Clean build branch
        run: |
          shopt -s extglob dotglob
          rm -r !(.git|CNAME|.|..)

      - name: Merge into build
        run: git merge -X theirs --no-commit ${{ github.sha }} --allow-unrelated-histories

      - name: Build Angular app
        run: |
          npm install
          npm run-script build

      - name: Clean up
        run: |
          shopt -s extglob dotglob
          rm -r !(dist|CNAME|.git|.|..)
          mv dist/*/* ./
          rm -r dist
